# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f3fc699c3bb8d87ae5a1034841ad43331502a8d43424d32d40c6ab98f065719c69c65e243fe22490e62b97589f599296e01511045aca8b3b70b012f59726b30d

test:
  secret_key_base: 9b02816a4f9d32dd1cd74666e8c38260c9af981db2bc83a58f55b6d38ee619e08fc67b8751e31dffcef194fe17bc31204bdd5b1a7ceb55ba0ea0c5e33bf3076c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
